// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitSnapshot } from "./RateLimitSnapshot";
import type { SpendControlLimitUpdate } from "./SpendControlLimitUpdate";

export type AccountRateLimitsUpdatedNotification = { rateLimits: RateLimitSnapshot,
/**
 * Sparse spend-control update carried alongside the backward-compatible snapshot.
 *
 * `unchanged` preserves cached metadata when rolling rate-limit headers omit account metadata
 * learned from `account/rateLimits/read`.
 */
individualLimitUpdate: SpendControlLimitUpdate, };
