// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpendControlLimitSnapshot } from "./SpendControlLimitSnapshot";

export type SpendControlLimitUpdate = { "type": "unchanged" } | { "type": "cleared" } | { "type": "updated", limit: SpendControlLimitSnapshot, };
